### ISSUE TITLE
Prepare Efficient Net to run live on jetson

### ISSUE THREAD

**Issue by CarlosGual** [curso-verano-iot-uah/iot-segmentations#10]

**Comment by msalexms** [comment]
Ya he conseguido que funcione. Tarda unos 40 segundos por epoch. En mi portatil eran casi 4 minutos :')
Lo tengo en local, cuando termine de porbar todo bien creo una branch

![Image](https://github.com/curso-verano-iot-uah/iot-segmentations/assets/91533700/16d44434-35ce-485d-8d20-1f1dd8fd4969)

**Comment by CarlosGual** [comment]
@msalexms give priority to this task so we can have both the esp (with MobileNet) and the Jetson (with EfficientNet and/or ResNet18) prepared to show them live to CEPSA this week.

**Comment by msalexms** [comment]
Okay, I'll stay home today because I have an exam tomorrow at 8am.
